export const airlineNames = {
  LY: 'El Al Israel Airlines',
  TK: 'Turkish Airlines',
  EK: 'Emirates',
  RJ: 'Royal Jordanian',
  ET: 'Ethiopian Airlines',
  FZ: 'FlyDubai',
  CY: 'Cyprus Airways',
  SU: 'Aeroflot',
  OS: 'Austrian Airlines',
  LH: 'Lufthansa',
  AF: 'Air France',
  KL: 'KLM',
  BA: 'British Airways',
  QR: 'Qatar Airways',
  EY: 'Etihad Airways',
  NH: 'All Nippon Airways',
  SQ: 'Singapore Airlines',
  CX: 'Cathay Pacific',
  TG: 'Thai Airways',
  AI: 'Air India',
  HU: 'Hainan Airlines',
  CZ: 'China Southern',
  MU: 'China Eastern',
  '3U': 'Sichuan Airlines',
  HY: 'Uzbekistan Airways',
  AA: 'American Airlines',
  UA: 'United Airlines',
  DL: 'Delta Air Lines',
  WN: 'Southwest Airlines',
  AS: 'Alaska Airlines',
  B6: 'JetBlue Airways',
  AC: 'Air Canada',
  WS: 'WestJet',
  LA: 'LATAM Airlines',
  AV: 'Avianca',
  CM: 'Copa Airlines',
  AM: 'Aeromexico',
  G3: 'GOL Linhas Aereas',
  IB: 'Iberia',
  UX: 'Air Europa',
  AY: 'Finnair',
  SK: 'Scandinavian Airlines',
  LO: 'LOT Polish Airlines',
  TP: 'TAP Air Portugal',
  LX: 'Swiss International Air Lines',
  SN: 'Brussels Airlines',
  A3: 'Aegean Airlines',
  EI: 'Aer Lingus',
  BT: 'AirBaltic',
  JU: 'Air Serbia',
  VY: 'Vueling',
  U2: 'easyJet',
  FR: 'Ryanair',
  DY: 'Norwegian Air Shuttle',
  W6: 'Wizz Air',
  W4: 'Wizz Air Malta',
  PC: 'Pegasus Airlines',
  QF: 'Qantas',
  NZ: 'Air New Zealand',
  VA: 'Virgin Australia',
  VS: 'Virgin Atlantic',
  JL: 'Japan Airlines',
  KE: 'Korean Air',
  OZ: 'Asiana Airlines',
  VN: 'Vietnam Airlines',
  MH: 'Malaysia Airlines',
  GA: 'Garuda Indonesia',
  BR: 'EVA Air',
  CI: 'China Airlines',
  WY: 'Oman Air',
  SV: 'Saudia',
  KU: 'Kuwait Airways',
  GF: 'Gulf Air',
  ME: 'Middle East Airlines',
  UL: 'SriLankan Airlines',
  SA: 'South African Airways',
  MS: 'Egyptair',
  OK: 'Czech Airlines',
  RO: 'TAROM',
  OU: 'Croatia Airlines',
  IZ: 'Arkia Israeli Airlines',
  '6H': 'Israir Airlines',
  '5C': 'CAL Cargo Airlines',
  '2U': "Sun d'Or Airlines",
  U8: 'Tus Airways',
  X7: 'Challenge Airlines IL',
  AZ: 'ITA Airways',
  EW: 'Eurowings',
  LS: 'Jet2.com',
  QS: 'Smartwings',
  NO: 'Neos',
  F9: 'Frontier Airlines',
  NK: 'Spirit Airlines',
  HA: 'Hawaiian Airlines',
  TS: 'Air Transat',
  VB: 'Viva Aerobus',
  Y4: 'Volaris',
  AD: 'Azul Brazilian Airlines',
  AR: 'Aerolineas Argentinas',
  H2: 'Sky Airline',
  PR: 'Philippine Airlines',
  AK: 'AirAsia',
  '5J': 'Cebu Pacific',
  KQ: 'Kenya Airways',
  AT: 'Royal Air Maroc',
  TU: 'Tunisair',
  MK: 'Air Mauritius',
  WB: 'RwandAir',
  CA: 'Air China',
  JQ: 'Jetstar Airways',
  V7: 'Volotea',
  DE: 'Condor',
  X3: 'TUI fly Germany',
  BY: 'TUI Airways',
  HV: 'Transavia',
  RK: 'Ryanair UK',
  G4: 'Allegiant Air',
  SY: 'Sun Country Airlines',
  TR: 'Scoot',
  SL: 'Thai Lion Air',
  VZ: 'Thai VietJet Air',
  OD: 'Batik Air Malaysia',
  MM: 'Peach Aviation',
  JJ: 'LATAM Brasil',
  FO: 'Flybondi',
  JA: 'JetSMART',
  DT: 'TAAG Angola Airlines',
  KP: 'ASKY Airlines',
  A9: 'Georgian Airways',
  AE: 'Mandarin Airlines',
  AH: 'Air Algerie',
  B2: 'Belavia',
  BG: 'Biman Bangladesh Airlines',
  BI: 'Royal Brunei Airlines',
  BP: 'Air Botswana',
  BS: 'US-Bangla Airlines',
  BW: 'Caribbean Airlines',
  BX: 'Air Busan',
  BZ: 'Blue Bird Airways',
  '3L': 'Air Arabia Abu Dhabi',
  '3O': 'Air Arabia Maroc',
  '5W': 'Wizz Air Abu Dhabi',
  D8: 'Norwegian Air Sweden',
  D7: 'AirAsia X',
  DM: 'Arajet',
  E2: 'Eurowings Europe',
  E5: 'Air Arabia Egypt',
  EN: 'Air Dolomiti',
  FB: 'Bulgaria Air',
  FH: 'Freebird Airlines',
  FI: 'Icelandair',
  FN: 'Fastjet',
  FQ: 'FlySafair',
  FY: 'Firefly',
  G9: 'Air Arabia',
  GK: 'Jetstar Japan',
  GL: 'Air Greenland',
  GQ: 'SKY express',
  GS: 'Tianjin Airlines',
  GX: 'GX Airlines',
  H9: 'Himalaya Airlines',
  HM: 'Air Seychelles',
  HO: 'Juneyao Airlines',
  HR: 'Hahn Air',
  I2: 'Iberia Express',
  IX: 'Air India Express',
  J2: 'Azerbaijan Airlines',
  J9: 'Jazeera Airways',
  JD: 'Beijing Capital Airlines',
  JE: 'Airlink',
  JI: 'Armenian Airlines',
  JT: 'Lion Air',
  KC: 'Air Astana',
  KM: 'KM Malta Airlines',
  KN: 'China United Airlines',
  KY: 'Kunming Airlines',
  LG: 'Luxair',
  LM: 'Loganair',
  MF: 'XiamenAir',
  NE: 'Nesma Airlines',
  NP: 'Nile Air',
  NX: 'Air Macau',
  OE: 'Lauda Europe',
  OM: 'MIAT Mongolian Airlines',
  OR: 'TUI fly Netherlands',
  OV: 'SalamAir',
  PG: 'Bangkok Airways',
  PK: 'Pakistan International Airlines',
  PN: 'West Air',
  PX: 'Air Niugini',
  QG: 'Citilink',
  QH: 'Bamboo Airways',
  QP: 'Akasa Air',
  R3: 'Yakutia Airlines',
  RA: 'Nepal Airlines',
  RB: 'Syrian Air',
  S4: 'Azores Airlines',
  S7: 'S7 Airlines',
  SC: 'Shandong Airlines',
  SG: 'SpiceJet',
  SM: 'Air Cairo',
  SP: 'SATA Air Acores',
  SS: 'Corsair',
  T5: 'Turkmenistan Airlines',
  TA: 'Avianca El Salvador',
  TC: 'Air Tanzania',
  TF: 'Braathens Regional Airlines',
  TO: 'Transavia France',
  U6: 'Ural Airlines',
  UK: 'Vistara',
  UT: 'UTair Aviation',
  VF: 'AJet',
  VJ: 'VietJet Air',
  VQ: 'Novoair',
  VR: 'Cabo Verde Airlines',
  WF: 'Wideroe',
  WM: 'Winair',
  XC: 'Corendon Airlines',
  XQ: 'SunExpress',
  XY: 'Flynas',
  YM: 'Air Montenegro',
  Z2: 'Philippines AirAsia',
  ZB: 'Air Albania',
  ZH: 'Shenzhen Airlines',
  ZL: 'Rex Airlines',
  '4Y': 'Discover Airlines',
  '5F': 'FlyOne',
  '7C': 'Jeju Air',
  '8M': 'Myanmar Airways International',
  '9C': 'Spring Airlines',
}
