export const airlineNames = {
  LY: 'El Al Israel Airlines',
  TK: 'Turkish Airlines',
  EK: 'Emirates',
  RJ: 'Royal Jordanian',
  ET: 'Ethiopian Airlines',
  FZ: 'FlyDubai',
  SU: 'Aeroflot',
  OS: 'Austrian Airlines',
  LH: 'Lufthansa',
  AF: 'Air France',
  KL: 'KLM',
  BA: 'British Airways',
  QR: 'Qatar Airways',
  EY: 'Etihad Airways',
  NH: 'All Nippon Airways',
  SQ: 'Singapore Airlines',
  CX: 'Cathay Pacific',
  TG: 'Thai Airways',
  AI: 'Air India',
  HU: 'Hainan Airlines',
  CZ: 'China Southern',
  MU: 'China Eastern',
  '3U': 'Sichuan Airlines',
  HY: 'Uzbekistan Airways',
  AA: 'American Airlines',
  UA: 'United Airlines',
  DL: 'Delta Air Lines',
  WN: 'Southwest Airlines',
  AS: 'Alaska Airlines',
  B6: 'JetBlue Airways',
  AC: 'Air Canada',
  WS: 'WestJet',
  LA: 'LATAM Airlines',
  AV: 'Avianca',
  CM: 'Copa Airlines',
  AM: 'Aeromexico',
  G3: 'GOL Linhas Aereas',
  IB: 'Iberia',
  UX: 'Air Europa',
  AY: 'Finnair',
  SK: 'Scandinavian Airlines',
  LO: 'LOT Polish Airlines',
  TP: 'TAP Air Portugal',
  LX: 'Swiss International Air Lines',
  SN: 'Brussels Airlines',
  A3: 'Aegean Airlines',
  EI: 'Aer Lingus',
  BT: 'AirBaltic',
  VY: 'Vueling',
  U2: 'easyJet',
  FR: 'Ryanair',
  DY: 'Norwegian Air Shuttle',
  W6: 'Wizz Air',
  PC: 'Pegasus Airlines',
  QF: 'Qantas',
  NZ: 'Air New Zealand',
  VA: 'Virgin Australia',
  VS: 'Virgin Atlantic',
  JL: 'Japan Airlines',
  KE: 'Korean Air',
  OZ: 'Asiana Airlines',
  VN: 'Vietnam Airlines',
  MH: 'Malaysia Airlines',
  GA: 'Garuda Indonesia',
  BR: 'EVA Air',
  CI: 'China Airlines',
  WY: 'Oman Air',
  SV: 'Saudia',
  KU: 'Kuwait Airways',
  GF: 'Gulf Air',
  ME: 'Middle East Airlines',
  UL: 'SriLankan Airlines',
  SA: 'South African Airways',
  MS: 'Egyptair',
  OK: 'Czech Airlines',
  RO: 'TAROM',
  OU: 'Croatia Airlines',
  IZ: 'Arkia Israeli Airlines',
  '6H': 'Israir Airlines',
  '5C': 'CAL Cargo Airlines',
  '2U': "Sun d'Or Airlines",
  U8: 'Tus Airways',
  X7: 'Challenge Airlines IL',
  AZ: 'ITA Airways',
  EW: 'Eurowings',
  LS: 'Jet2.com',
  F9: 'Frontier Airlines',
  NK: 'Spirit Airlines',
  HA: 'Hawaiian Airlines',
  TS: 'Air Transat',
  VB: 'Viva Aerobus',
  Y4: 'Volaris',
  AD: 'Azul Brazilian Airlines',
  AR: 'Aerolineas Argentinas',
  H2: 'Sky Airline',
  PR: 'Philippine Airlines',
  AK: 'AirAsia',
  '5J': 'Cebu Pacific',
  KQ: 'Kenya Airways',
  AT: 'Royal Air Maroc',
  TU: 'Tunisair',
  MK: 'Air Mauritius',
  WB: 'RwandAir',
  CA: 'Air China',
  JQ: 'Jetstar Airways',
}
