// src/services/airport.service.js

export const AIRPORT_OPTIONS = [
  { code: 'TLV', label: 'Tel Aviv, Israel' },
  { code: 'HFA', label: 'Haifa, Israel' },
  { code: 'ETH', label: 'Eilat (Ramon), Israel' },
  { code: 'ETM', label: 'Eilat (Ramon), Israel' },
  { code: 'LCA', label: 'Larnaca, Cyprus' },
  { code: 'PFO', label: 'Paphos, Cyprus' },
  { code: 'ATH', label: 'Athens, Greece' },
  { code: 'HER', label: 'Heraklion, Greece' },
  { code: 'CHQ', label: 'Chania, Greece' },
  { code: 'RHO', label: 'Rhodes, Greece' },
  { code: 'KGS', label: 'Kos, Greece' },
  { code: 'CFU', label: 'Corfu, Greece' },
  { code: 'JTR', label: 'Santorini, Greece' },
  { code: 'JMK', label: 'Mykonos, Greece' },
  { code: 'IST', label: 'Istanbul, Turkey' },
  { code: 'SAW', label: 'Istanbul (Sabiha), Turkey' },
  { code: 'AYT', label: 'Antalya, Turkey' },
  { code: 'BJV', label: 'Bodrum, Turkey' },
  { code: 'ADB', label: 'Izmir, Turkey' },
  { code: 'DLM', label: 'Dalaman, Turkey' },
  { code: 'DXB', label: 'Dubai, UAE' },
  { code: 'AUH', label: 'Abu Dhabi, UAE' },
  { code: 'DOH', label: 'Doha, Qatar' },
  { code: 'FCO', label: 'Rome, Italy' },
  { code: 'MXP', label: 'Milan, Italy' },
  { code: 'CDG', label: 'Paris, France' },
  { code: 'AMS', label: 'Amsterdam, Netherlands' },
  { code: 'FRA', label: 'Frankfurt, Germany' },
  { code: 'MUC', label: 'Munich, Germany' },
  { code: 'ZRH', label: 'Zurich, Switzerland' },
  { code: 'LHR', label: 'London (Heathrow), UK' },
  { code: 'LGW', label: 'London (Gatwick), UK' },
  { code: 'MAD', label: 'Madrid, Spain' },
  { code: 'BCN', label: 'Barcelona, Spain' },
  { code: 'BKK', label: 'Bangkok, Thailand' },
  { code: 'HKT', label: 'Phuket, Thailand' },
  { code: 'CNX', label: 'Chiang Mai, Thailand' },
  { code: 'SIN', label: 'Singapore' },
  { code: 'HND', label: 'Tokyo (Haneda), Japan' },
  { code: 'NRT', label: 'Tokyo (Narita), Japan' },
  { code: 'KIX', label: 'Osaka (Kansai), Japan' },
  { code: 'ICN', label: 'Seoul (Incheon), South Korea' },
  { code: 'JFK', label: 'New York (JFK), USA' },
  { code: 'EWR', label: 'Newark, USA' },
  { code: 'LAX', label: 'Los Angeles, USA' },
  { code: 'SFO', label: 'San Francisco, USA' },
  { code: 'ORD', label: "Chicago (O'Hare), USA" },
  { code: 'ATL', label: 'Atlanta, USA' },
  { code: 'DFW', label: 'Dallas/Fort Worth, USA' },
  { code: 'MIA', label: 'Miami, USA' },
  { code: 'BOS', label: 'Boston, USA' },
  { code: 'SEA', label: 'Seattle, USA' },
  { code: 'DEN', label: 'Denver, USA' },
  { code: 'LAS', label: 'Las Vegas, USA' },
  { code: 'YYZ', label: 'Toronto, Canada' },
  { code: 'YUL', label: 'Montreal, Canada' },
  { code: 'DUB', label: 'Dublin, Ireland' },
  { code: 'LIS', label: 'Lisbon, Portugal' },
  { code: 'OPO', label: 'Porto, Portugal' },
  { code: 'BRU', label: 'Brussels, Belgium' },
  { code: 'VIE', label: 'Vienna, Austria' },
  { code: 'ARN', label: 'Stockholm, Sweden' },
  { code: 'CPH', label: 'Copenhagen, Denmark' },
  { code: 'OSL', label: 'Oslo, Norway' },
  { code: 'HKG', label: 'Hong Kong' },
  { code: 'SYD', label: 'Sydney, Australia' },
  { code: 'MEL', label: 'Melbourne, Australia' },
  { code: 'PVG', label: 'Shanghai (Pudong), China' },
  { code: 'PEK', label: 'Beijing (Capital), China' },
  { code: 'CAN', label: 'Guangzhou, China' },
  { code: 'SZX', label: 'Shenzhen, China' },
  { code: 'TPE', label: 'Taipei, Taiwan' },
  { code: 'KUL', label: 'Kuala Lumpur, Malaysia' },
  { code: 'CGK', label: 'Jakarta, Indonesia' },
  { code: 'DPS', label: 'Bali (Denpasar), Indonesia' },
  { code: 'MNL', label: 'Manila, Philippines' },
  { code: 'DEL', label: 'Delhi, India' },
  { code: 'BOM', label: 'Mumbai, India' },
  { code: 'BLR', label: 'Bangalore, India' },
  { code: 'HYD', label: 'Hyderabad, India' },
  { code: 'MAA', label: 'Chennai, India' },
  { code: 'RUH', label: 'Riyadh, Saudi Arabia' },
  { code: 'JED', label: 'Jeddah, Saudi Arabia' },
  { code: 'IAH', label: 'Houston, USA' },
  { code: 'PHX', label: 'Phoenix, USA' },
  { code: 'MCO', label: 'Orlando, USA' },
  { code: 'IAD', label: 'Washington Dulles, USA' },
  { code: 'PHL', label: 'Philadelphia, USA' },
  { code: 'MSP', label: 'Minneapolis, USA' },
  { code: 'SLC', label: 'Salt Lake City, USA' },
  { code: 'CLT', label: 'Charlotte, USA' },
  { code: 'DTW', label: 'Detroit, USA' },
  { code: 'YVR', label: 'Vancouver, Canada' },
  { code: 'YYC', label: 'Calgary, Canada' },
  { code: 'MEX', label: 'Mexico City, Mexico' },
  { code: 'CUN', label: 'Cancun, Mexico' },
  { code: 'GDL', label: 'Guadalajara, Mexico' },
  { code: 'PTY', label: 'Panama City, Panama' },
  { code: 'SJO', label: 'San Jose, Costa Rica' },
  { code: 'BOG', label: 'Bogota, Colombia' },
  { code: 'MDE', label: 'Medellin, Colombia' },
  { code: 'LIM', label: 'Lima, Peru' },
  { code: 'SCL', label: 'Santiago, Chile' },
  { code: 'EZE', label: 'Buenos Aires, Argentina' },
  { code: 'GRU', label: 'Sao Paulo, Brazil' },
  { code: 'GIG', label: 'Rio de Janeiro, Brazil' },
  { code: 'CAI', label: 'Cairo, Egypt' },
  { code: 'CMN', label: 'Casablanca, Morocco' },
  { code: 'RAK', label: 'Marrakesh, Morocco' },
  { code: 'AGA', label: 'Agadir, Morocco' },
  { code: 'TUN', label: 'Tunis, Tunisia' },
  { code: 'NBO', label: 'Nairobi, Kenya' },
  { code: 'ADD', label: 'Addis Ababa, Ethiopia' },
  { code: 'JNB', label: 'Johannesburg, South Africa' },
  { code: 'CPT', label: 'Cape Town, South Africa' },
  { code: 'LOS', label: 'Lagos, Nigeria' },
  { code: 'ACC', label: 'Accra, Ghana' },
  { code: 'DAR', label: 'Dar es Salaam, Tanzania' },
  { code: 'MRU', label: 'Mauritius' },
  { code: 'BER', label: 'Berlin, Germany' },
  { code: 'HAM', label: 'Hamburg, Germany' },
  { code: 'DUS', label: 'Düsseldorf, Germany' },
  { code: 'PRG', label: 'Prague, Czech Republic' },
  { code: 'BUD', label: 'Budapest, Hungary' },
  { code: 'WAW', label: 'Warsaw, Poland' },
  { code: 'KRK', label: 'Krakow, Poland' },
  { code: 'KTW', label: 'Katowice, Poland' },
  { code: 'GDN', label: 'Gdansk, Poland' },
  { code: 'ZAG', label: 'Zagreb, Croatia' },
  { code: 'LJU', label: 'Ljubljana, Slovenia' },
  { code: 'SOF', label: 'Sofia, Bulgaria' },
  { code: 'OTP', label: 'Bucharest, Romania' },
  { code: 'SKG', label: 'Thessaloniki, Greece' },
  { code: 'NAP', label: 'Naples, Italy' },
  { code: 'VCE', label: 'Venice, Italy' },
  { code: 'LIN', label: 'Milan (Linate), Italy' },
  { code: 'MAN', label: 'Manchester, UK' },
  { code: 'EDI', label: 'Edinburgh, UK' },
  { code: 'GLA', label: 'Glasgow, UK' },
  { code: 'HEL', label: 'Helsinki, Finland' },
  { code: 'RIX', label: 'Riga, Latvia' },
  { code: 'VNO', label: 'Vilnius, Lithuania' },
  { code: 'TLL', label: 'Tallinn, Estonia' },
  { code: 'EVN', label: 'Yerevan, Armenia' },
  { code: 'TBS', label: 'Tbilisi, Georgia' },
  { code: 'SAN', label: 'San Diego, USA' },
  { code: 'SJC', label: 'San Jose, USA' },
  { code: 'OAK', label: 'Oakland, USA' },
  { code: 'TPA', label: 'Tampa, USA' },
  { code: 'FLL', label: 'Fort Lauderdale, USA' },
  { code: 'BWI', label: 'Baltimore, USA' },
  { code: 'DCA', label: 'Washington (Reagan), USA' },
  { code: 'RDU', label: 'Raleigh-Durham, USA' },
  { code: 'PDX', label: 'Portland, USA' },
  { code: 'ANC', label: 'Anchorage, USA' },
  { code: 'YOW', label: 'Ottawa, Canada' },
  { code: 'YHZ', label: 'Halifax, Canada' },
  { code: 'MFM', label: 'Macau' },
  { code: 'ITM', label: 'Osaka (Itami), Japan' },
  { code: 'FUK', label: 'Fukuoka, Japan' },
  { code: 'OKA', label: 'Okinawa, Japan' },
  { code: 'CTS', label: 'Sapporo, Japan' },
  { code: 'SGN', label: 'Ho Chi Minh City, Vietnam' },
  { code: 'HAN', label: 'Hanoi, Vietnam' },
  { code: 'DAD', label: 'Da Nang, Vietnam' },
  { code: 'PNH', label: 'Phnom Penh, Cambodia' },
  { code: 'REP', label: 'Siem Reap, Cambodia' },
  { code: 'ULN', label: 'Ulaanbaatar, Mongolia' },
  { code: 'ALA', label: 'Almaty, Kazakhstan' },
  { code: 'TAS', label: 'Tashkent, Uzbekistan' },
  { code: 'UIO', label: 'Quito, Ecuador' },
  { code: 'GYE', label: 'Guayaquil, Ecuador' },
  { code: 'LPB', label: 'La Paz, Bolivia' },
  { code: 'ASU', label: 'Asunción, Paraguay' },
  { code: 'MVD', label: 'Montevideo, Uruguay' },
  { code: 'SDQ', label: 'Santo Domingo, Dominican Republic' },
  { code: 'HAV', label: 'Havana, Cuba' },
  { code: 'SHJ', label: 'Sharjah, UAE' },
  { code: 'AMM', label: 'Amman, Jordan' },
  { code: 'BEY', label: 'Beirut, Lebanon' },
  { code: 'KWI', label: 'Kuwait City, Kuwait' },
  { code: 'BAH', label: 'Manama, Bahrain' },
  { code: 'ALG', label: 'Algiers, Algeria' },
  { code: 'DKR', label: 'Dakar, Senegal' },
  { code: 'ABJ', label: 'Abidjan, Ivory Coast' },
  { code: 'KGL', label: 'Kigali, Rwanda' },
  { code: 'PMI', label: 'Palma de Mallorca, Spain' },
  { code: 'BLQ', label: 'Bologna, Italy' },
  { code: 'GOT', label: 'Gothenburg, Sweden' },
  { code: 'GVA', label: 'Geneva, Switzerland' },
  { code: 'SNA', label: 'Orange County, USA' },
  { code: 'AUS', label: 'Austin, USA' },
  { code: 'SMF', label: 'Sacramento, USA' },
  { code: 'GMP', label: 'Seoul (Gimpo), South Korea' },
  { code: 'CTU', label: 'Chengdu, China' },
  { code: 'DMK', label: 'Bangkok (Don Mueang), Thailand' },
  { code: 'BRC', label: 'San Carlos de Bariloche, Argentina' },
  { code: 'PUJ', label: 'Punta Cana, Dominican Republic' },
  { code: 'LGA', label: 'New York (LaGuardia), USA' },
  { code: 'MDW', label: 'Chicago (Midway), USA' },
  { code: 'HOU', label: 'Houston (Hobby), USA' },
  { code: 'DAL', label: 'Dallas (Love Field), USA' },
  { code: 'SAT', label: 'San Antonio, USA' },
  { code: 'BNA', label: 'Nashville, USA' },
  { code: 'STL', label: 'St. Louis, USA' },
  { code: 'MCI', label: 'Kansas City, USA' },
  { code: 'IND', label: 'Indianapolis, USA' },
  { code: 'CMH', label: 'Columbus, USA' },
  { code: 'CLE', label: 'Cleveland, USA' },
  { code: 'PIT', label: 'Pittsburgh, USA' },
  { code: 'CVG', label: 'Cincinnati, USA' },
  { code: 'JAX', label: 'Jacksonville, USA' },
  { code: 'MSY', label: 'New Orleans, USA' },
  { code: 'MEM', label: 'Memphis, USA' },
  { code: 'OMA', label: 'Omaha, USA' },
  { code: 'ABQ', label: 'Albuquerque, USA' },
  { code: 'TUS', label: 'Tucson, USA' },
  { code: 'RNO', label: 'Reno, USA' },
  { code: 'BOI', label: 'Boise, USA' },
  { code: 'GEG', label: 'Spokane, USA' },
  { code: 'PSP', label: 'Palm Springs, USA' },
  { code: 'BUR', label: 'Burbank, USA' },
  { code: 'ONT', label: 'Ontario, USA' },
  { code: 'LGB', label: 'Long Beach, USA' },
  { code: 'HNL', label: 'Honolulu, USA' },
  { code: 'OGG', label: 'Maui (Kahului), USA' },
  { code: 'KOA', label: 'Kona, USA' },
  { code: 'LIH', label: 'Kauai (Lihue), USA' },
  { code: 'YEG', label: 'Edmonton, Canada' },
  { code: 'YWG', label: 'Winnipeg, Canada' },
  { code: 'YQB', label: 'Quebec City, Canada' },
  { code: 'YXE', label: 'Saskatoon, Canada' },
  { code: 'YQR', label: 'Regina, Canada' },
  { code: 'YYT', label: "St. John's, Canada" },
  { code: 'YTZ', label: 'Toronto (Billy Bishop), Canada' },
  { code: 'YLW', label: 'Kelowna, Canada' },
  { code: 'YMM', label: 'Fort McMurray, Canada' },
  { code: 'ORY', label: 'Paris (Orly), France' },
  { code: 'NCE', label: 'Nice, France' },
  { code: 'LYS', label: 'Lyon, France' },
  { code: 'TLS', label: 'Toulouse, France' },
  { code: 'MRS', label: 'Marseille, France' },
  { code: 'BOD', label: 'Bordeaux, France' },
  { code: 'NTE', label: 'Nantes, France' },
  { code: 'BSL', label: 'Basel, Switzerland' },
  { code: 'STR', label: 'Stuttgart, Germany' },
  { code: 'CGN', label: 'Cologne/Bonn, Germany' },
  { code: 'NUE', label: 'Nuremberg, Germany' },
  { code: 'HAJ', label: 'Hannover, Germany' },
  { code: 'LEJ', label: 'Leipzig/Halle, Germany' },
  { code: 'BRE', label: 'Bremen, Germany' },
  { code: 'AGP', label: 'Malaga, Spain' },
  { code: 'ALC', label: 'Alicante, Spain' },
  { code: 'VLC', label: 'Valencia, Spain' },
  { code: 'SVQ', label: 'Seville, Spain' },
  { code: 'BIO', label: 'Bilbao, Spain' },
  { code: 'IBZ', label: 'Ibiza, Spain' },
  { code: 'TFS', label: 'Tenerife South, Spain' },
  { code: 'LPA', label: 'Gran Canaria, Spain' },
  { code: 'CTA', label: 'Catania, Italy' },
  { code: 'PMO', label: 'Palermo, Italy' },
  { code: 'BRI', label: 'Bari, Italy' },
  { code: 'CAG', label: 'Cagliari, Italy' },
  { code: 'TRN', label: 'Turin, Italy' },
  { code: 'PSA', label: 'Pisa, Italy' },
  { code: 'FLR', label: 'Florence, Italy' },
  { code: 'GOA', label: 'Genoa, Italy' },
  { code: 'BHX', label: 'Birmingham, UK' },
  { code: 'BRS', label: 'Bristol, UK' },
  { code: 'DME', label: 'Moscow (Domodedovo), Russia' },
  { code: 'SVO', label: 'Moscow (Sheremetyevo), Russia' },
  { code: 'LTN', label: 'London (Luton), UK' },
  { code: 'STN', label: 'London (Stansted), UK' },
  { code: 'LCY', label: 'London (City), UK' },
  { code: 'NCL', label: 'Newcastle, UK' },
  { code: 'BFS', label: 'Belfast, UK' },
  { code: 'ABZ', label: 'Aberdeen, UK' },
  { code: 'BGO', label: 'Bergen, Norway' },
  { code: 'TRD', label: 'Trondheim, Norway' },
  { code: 'SVG', label: 'Stavanger, Norway' },
  { code: 'KEF', label: 'Reykjavik (Keflavik), Iceland' },
  { code: 'BEG', label: 'Belgrade, Serbia' },
  { code: 'TIA', label: 'Tirana, Albania' },
  { code: 'DBV', label: 'Dubrovnik, Croatia' },
  { code: 'SPU', label: 'Split, Croatia' },
  { code: 'SJJ', label: 'Sarajevo, Bosnia and Herzegovina' },
  { code: 'SKP', label: 'Skopje, North Macedonia' },
  { code: 'KIV', label: 'Chisinau, Moldova' },
  { code: 'IAS', label: 'Iasi, Romania' },
  { code: 'CLJ', label: 'Cluj-Napoca, Romania' },
  { code: 'TSR', label: 'Timisoara, Romania' },
  { code: 'VAR', label: 'Varna, Bulgaria' },
  { code: 'BOJ', label: 'Burgas, Bulgaria' },
  { code: 'MED', label: 'Medina, Saudi Arabia' },
  { code: 'DMM', label: 'Dammam, Saudi Arabia' },
  { code: 'MCT', label: 'Muscat, Oman' },
  { code: 'SSH', label: 'Sharm El Sheikh, Egypt' },
  { code: 'HRG', label: 'Hurghada, Egypt' },
  { code: 'IKA', label: 'Tehran (Imam Khomeini), Iran' },
  { code: 'BGW', label: 'Baghdad, Iraq' },
  { code: 'EBL', label: 'Erbil, Iraq' },
  { code: 'KHI', label: 'Karachi, Pakistan' },
  { code: 'LHE', label: 'Lahore, Pakistan' },
  { code: 'ISB', label: 'Islamabad, Pakistan' },
  { code: 'KTM', label: 'Kathmandu, Nepal' },
  { code: 'DAC', label: 'Dhaka, Bangladesh' },
  { code: 'CMB', label: 'Colombo, Sri Lanka' },
  { code: 'MLE', label: 'Male, Maldives' },
  { code: 'CCU', label: 'Kolkata, India' },
  { code: 'COK', label: 'Kochi, India' },
  { code: 'GOI', label: 'Goa, India' },
  { code: 'AMD', label: 'Ahmedabad, India' },
  { code: 'PNQ', label: 'Pune, India' },
  { code: 'TRV', label: 'Thiruvananthapuram, India' },
  { code: 'ATQ', label: 'Amritsar, India' },
  { code: 'SUB', label: 'Surabaya, Indonesia' },
  { code: 'YIA', label: 'Yogyakarta, Indonesia' },
  { code: 'KNO', label: 'Medan, Indonesia' },
  { code: 'UPG', label: 'Makassar, Indonesia' },
  { code: 'LOP', label: 'Lombok, Indonesia' },
  { code: 'PEN', label: 'Penang, Malaysia' },
  { code: 'BKI', label: 'Kota Kinabalu, Malaysia' },
  { code: 'KCH', label: 'Kuching, Malaysia' },
  { code: 'LGK', label: 'Langkawi, Malaysia' },
  { code: 'KBV', label: 'Krabi, Thailand' },
  { code: 'USM', label: 'Koh Samui, Thailand' },
  { code: 'UTP', label: 'Pattaya (U-Tapao), Thailand' },
  { code: 'CEB', label: 'Cebu, Philippines' },
  { code: 'CRK', label: 'Clark, Philippines' },
  { code: 'DVO', label: 'Davao, Philippines' },
  { code: 'PUS', label: 'Busan, South Korea' },
  { code: 'CJU', label: 'Jeju, South Korea' },
  { code: 'PKX', label: 'Beijing (Daxing), China' },
  { code: 'SHA', label: 'Shanghai (Hongqiao), China' },
  { code: 'TFU', label: 'Chengdu (Tianfu), China' },
  { code: 'XIY', label: "Xi'an, China" },
  { code: 'CKG', label: 'Chongqing, China' },
  { code: 'HGH', label: 'Hangzhou, China' },
  { code: 'NKG', label: 'Nanjing, China' },
  { code: 'XMN', label: 'Xiamen, China' },
  { code: 'TAO', label: 'Qingdao, China' },
  { code: 'WUH', label: 'Wuhan, China' },
  { code: 'CSX', label: 'Changsha, China' },
  { code: 'KMG', label: 'Kunming, China' },
  { code: 'URC', label: 'Urumqi, China' },
  { code: 'NGO', label: 'Nagoya, Japan' },
  { code: 'SDJ', label: 'Sendai, Japan' },
  { code: 'HIJ', label: 'Hiroshima, Japan' },
  { code: 'KOJ', label: 'Kagoshima, Japan' },
  { code: 'BNE', label: 'Brisbane, Australia' },
  { code: 'PER', label: 'Perth, Australia' },
  { code: 'ADL', label: 'Adelaide, Australia' },
  { code: 'CBR', label: 'Canberra, Australia' },
  { code: 'OOL', label: 'Gold Coast, Australia' },
  { code: 'CNS', label: 'Cairns, Australia' },
  { code: 'DRW', label: 'Darwin, Australia' },
  { code: 'HBA', label: 'Hobart, Australia' },
  { code: 'AKL', label: 'Auckland, New Zealand' },
  { code: 'CHC', label: 'Christchurch, New Zealand' },
  { code: 'WLG', label: 'Wellington, New Zealand' },
  { code: 'ZQN', label: 'Queenstown, New Zealand' },
  { code: 'DUR', label: 'Durban, South Africa' },
  { code: 'PLZ', label: 'Gqeberha, South Africa' },
  { code: 'HRE', label: 'Harare, Zimbabwe' },
  { code: 'LUN', label: 'Lusaka, Zambia' },
  { code: 'LVI', label: 'Livingstone, Zambia' },
  { code: 'MPM', label: 'Maputo, Mozambique' },
  { code: 'WDH', label: 'Windhoek, Namibia' },
  { code: 'SEZ', label: 'Seychelles' },
  { code: 'ZNZ', label: 'Zanzibar, Tanzania' },
  { code: 'MBA', label: 'Mombasa, Kenya' },
  { code: 'EBB', label: 'Entebbe, Uganda' },
  { code: 'ABV', label: 'Abuja, Nigeria' },
  { code: 'BSB', label: 'Brasilia, Brazil' },
  { code: 'CGH', label: 'Sao Paulo (Congonhas), Brazil' },
  { code: 'VCP', label: 'Campinas, Brazil' },
  { code: 'CNF', label: 'Belo Horizonte, Brazil' },
  { code: 'SSA', label: 'Salvador, Brazil' },
  { code: 'REC', label: 'Recife, Brazil' },
  { code: 'FOR', label: 'Fortaleza, Brazil' },
  { code: 'POA', label: 'Porto Alegre, Brazil' },
  { code: 'CWB', label: 'Curitiba, Brazil' },
  { code: 'FLN', label: 'Florianopolis, Brazil' },
  { code: 'BEL', label: 'Belem, Brazil' },
  { code: 'MAO', label: 'Manaus, Brazil' },
  { code: 'AEP', label: 'Buenos Aires (Aeroparque), Argentina' },
  { code: 'COR', label: 'Cordoba, Argentina' },
  { code: 'MDZ', label: 'Mendoza, Argentina' },
  { code: 'USH', label: 'Ushuaia, Argentina' },
  { code: 'ANF', label: 'Antofagasta, Chile' },
  { code: 'PMC', label: 'Puerto Montt, Chile' },
  { code: 'CUZ', label: 'Cusco, Peru' },
  { code: 'CTG', label: 'Cartagena, Colombia' },
  { code: 'CLO', label: 'Cali, Colombia' },
  { code: 'MTY', label: 'Monterrey, Mexico' },
  { code: 'PVR', label: 'Puerto Vallarta, Mexico' },
  { code: 'SJD', label: 'San Jose del Cabo, Mexico' },
  { code: 'TIJ', label: 'Tijuana, Mexico' },
  { code: 'BJX', label: 'Leon/Guanajuato, Mexico' },
  { code: 'QRO', label: 'Queretaro, Mexico' },
  { code: 'MID', label: 'Merida, Mexico' },
  { code: 'OAX', label: 'Oaxaca, Mexico' },
  { code: 'GUA', label: 'Guatemala City, Guatemala' },
  { code: 'SAL', label: 'San Salvador, El Salvador' },
  { code: 'MGA', label: 'Managua, Nicaragua' },
  { code: 'BZE', label: 'Belize City, Belize' },
  { code: 'KIN', label: 'Kingston, Jamaica' },
  { code: 'MBJ', label: 'Montego Bay, Jamaica' },
  { code: 'POS', label: 'Port of Spain, Trinidad and Tobago' },
  { code: 'NAS', label: 'Nassau, Bahamas' },
  { code: 'AUA', label: 'Aruba' },
  { code: 'CUR', label: 'Curacao' },
]

export function getAirportOptions() {
  return AIRPORT_OPTIONS
}

export function buildAirportMap(options = AIRPORT_OPTIONS) {
  const map = new Map()
  options.forEach((o) => map.set(String(o.code).toUpperCase(), o))
  return map
}

export function normalizeCodes(value) {
  if (!value) return []
  if (Array.isArray(value)) return value.map((x) => String(x).trim()).filter(Boolean)

  if (typeof value === 'string') {
    return (value || '')
      .split(',')
      .map((x) => x.trim())
      .filter(Boolean)
  }

  return []
}

export function serializeCodes(codes) {
  return (codes || [])
    .map((c) => String(c).toUpperCase())
    .filter(Boolean)
    .join(', ')
}

export function filterAirportOptions(query, options = AIRPORT_OPTIONS) {
  const q = String(query || '').trim().toLowerCase()
  if (!q) return options

  return options.filter((o) => {
    const code = String(o.code || '').toLowerCase()
    const label = String(o.label || '').toLowerCase()
    return code.includes(q) || label.includes(q)
  })
}

export function codesToChips(codes, byCodeMap) {
  return (codes || [])
    .map((c) => String(c).toUpperCase())
    .filter(Boolean)
    .map((code) => ({ code, label: byCodeMap.get(code)?.label || code }))
}

export function isKnownCode(code, byCodeMap) {
  const upper = String(code || '').toUpperCase()
  return Boolean(upper && byCodeMap.has(upper))
}
